name = "iron-routine"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
main = "src/index.js"

[vars]
ENVIRONMENT = "development"

[env.production]
name = "iron-routine-prod"
vars = { ENVIRONMENT = "production" }

[env.staging]
name = "iron-routine-staging"
vars = { ENVIRONMENT = "staging" }